export const SPECIAL_OFFERS = [
  {
    id: 1,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Дизайн',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '15 февраля – 10 марта',
    fullText: 'У тебя есть студенческий? У нас есть повод порадоваться!\nЛюбишь атмосферу ЦЕХа, но хочешь экономить? Легко! Покажи корочку студента на кассе, и мы сделаем скидку 15%.\nДействуй по-студенчески: веселись, но с умом!\n\n*Предложение ограничено',
  },
  {
    id: 2,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'IT',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '1 марта – 30 марта',
    fullText: 'Ещё одно предложение для студентов.\n\n*Предложение ограничено',
  },
  {
    id: 3,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Контент',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '10 марта – 20 марта',
    fullText: 'Описание третьего предложения.\n\n*Предложение ограничено',
  },
  {
    id: 4,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Дизайн',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '5 марта – 25 марта',
    fullText: 'Описание четвёртого предложения.',
  },
  {
    id: 5,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Frontend',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '1 апреля – 30 апреля',
    fullText: 'Описание пятого предложения.',
  },
  {
    id: 6,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Backend',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '2 апреля – 15 апреля',
    fullText: 'Описание шестого предложения.',
  },
  {
    id: 7,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'IT',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '10 апреля – 30 апреля',
    fullText: 'Описание седьмого предложения.',
  },
  {
    id: 8,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Дизайн',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '15 апреля – 1 мая',
    fullText: 'Описание восьмого предложения.',
  },
  {
    id: 9,
    title: 'Скидка в ЦЕХ',
    percent: '15%',
    description: 'Предъявите студенческий при покупке и получите скидку',
    direction: 'Контент',
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&h=320&fit=crop',
    period: '1 мая – 20 мая',
    fullText: 'Описание девятого предложения.',
  },
];

export const OFFER_DIRECTIONS = [
  'Кафе', 'Frontend',
  'Контент',      'Backend',
  'Дизайн',       'Инженерия',
  'IT',           'Другое',
];
